#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Theme palette definitions used by the main application shell."""


THEME_DEFINITIONS = {
    "dark_visual_cs": {
        "label": "Dark Visual CS",
        "palette": {
            "bg": "#1e1e1e",
            "panel": "#252526",
            "panel_alt": "#2d2d30",
            "field": "#1a1a1a",
            "border": "#3c3c3c",
            "panel_border": "#313131",
            "fg": "#f3f3f3",
            "muted": "#c7c7c7",
            "muted_dim": "#9a9a9a",
            "accent": "#63c7ff",
            "accent_hover": "#89d7ff",
            "accent_selected": "#2c607d",
            "campaign_edge": "#2DD4BF",
            "button_hover": "#37373d",
            "tab_disabled_bg": "#1e1e1e",
            "tab_disabled_fg": "#6f6f6f",
            "success": "#4ec9b0",
            "warning": "#d7ba7d",
            "error": "#f48771",
            "surface_info": "#213a4d",
            "surface_success": "#1f3320",
            "surface_warning": "#3a2323",
            "guide": "#f0b44c",
            "guide_pulse": "#ffd37a",
            "guide_text": "#111111",
            "accent_text": "#ffffff",
            "console_bg": "#252526",
            "console_fg": "#f3f3f3",
            "console_border": "#3c3c3c",
            "doc_bg": "#1f1f1f",
            "doc_fg": "#f3f3f3",
            "code_bg": "#2d2d30",
            "code_fg": "#dcdcaa",
        },
    },
    "dark_graphite": {
        "label": "Dark Graphite",
        "palette": {
            "bg": "#202124",
            "panel": "#2a2b2f",
            "panel_alt": "#32343a",
            "field": "#191a1d",
            "border": "#404349",
            "panel_border": "#37393f",
            "fg": "#f5f5f5",
            "muted": "#d0d0d0",
            "muted_dim": "#9b9b9b",
            "accent": "#66b4ff",
            "accent_hover": "#8ac7ff",
            "accent_selected": "#355f86",
            "campaign_edge": "#2DD4BF",
            "button_hover": "#3a3c43",
            "tab_disabled_bg": "#202124",
            "tab_disabled_fg": "#76797f",
            "success": "#62d2a2",
            "warning": "#e3c27a",
            "error": "#ff8e72",
            "surface_info": "#2b3f54",
            "surface_success": "#22362c",
            "surface_warning": "#3b2f1e",
            "guide": "#f3c96b",
            "guide_pulse": "#ffe29a",
            "guide_text": "#111111",
            "accent_text": "#ffffff",
            "console_bg": "#2a2b2f",
            "console_fg": "#f5f5f5",
            "console_border": "#404349",
            "doc_bg": "#25262a",
            "doc_fg": "#f5f5f5",
            "code_bg": "#32343a",
            "code_fg": "#f6d28b",
        },
    },
    "light_visual_cs": {
        "label": "Light Visual CS",
        "palette": {
            "bg": "#f3f3f3",
            "panel": "#ffffff",
            "panel_alt": "#e7e7e7",
            "field": "#ffffff",
            "border": "#c8c8c8",
            "panel_border": "#dcdcdc",
            "fg": "#1f1f1f",
            "muted": "#4f4f4f",
            "muted_dim": "#7a7a7a",
            "accent": "#006bb3",
            "accent_hover": "#0b7dcd",
            "accent_selected": "#00548c",
            "campaign_edge": "#0F9F9A",
            "button_hover": "#e1edf7",
            "tab_disabled_bg": "#e3e3e3",
            "tab_disabled_fg": "#989898",
            "success": "#1f8f6b",
            "warning": "#b57900",
            "error": "#c7422f",
            "surface_info": "#eaf3ff",
            "surface_success": "#e8f6ef",
            "surface_warning": "#fff4d9",
            "guide": "#ffd86b",
            "guide_pulse": "#ffebad",
            "guide_text": "#1f1f1f",
            "accent_text": "#ffffff",
            "console_bg": "#ffffff",
            "console_fg": "#1f1f1f",
            "console_border": "#c8c8c8",
            "doc_bg": "#ffffff",
            "doc_fg": "#1f1f1f",
            "code_bg": "#f3f3f3",
            "code_fg": "#8b3f00",
        },
    },
}
