#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Moduł rankingu.
"""

from .annotation_comparator import AnnotationComparator, AnnotationDiff
from .corner_metrics import (
    CORNER_METRIC_SCHEMA,
    corner_metric_protocol_descriptor,
    evaluate_pose_corner_metrics,
)
from .comparison_catalog import (
    ModelComparisonCandidate,
    ModelComparisonCatalog,
    SCOPE_PROJECT,
    SCOPE_WORKSPACE,
    active_project_id_from_root,
    comparison_scope_label,
    normalize_comparison_scope,
)
from .experiment_bridge import (
    RankingExperimentBridge,
    RankingExperimentContext,
    RankingExperimentParticipant,
)
from .legacy_compatibility import (
    EVIDENCE_CONTROLLED,
    EVIDENCE_CONTROLLED_LEGACY,
    EVIDENCE_LEGACY,
    EVIDENCE_MISMATCH,
    EVIDENCE_ORPHANED,
    EVIDENCE_REGISTERED_INCOMPLETE,
    EVIDENCE_WORKING,
    RankingRegistryCompatibility,
    RankingRegistryReconciliation,
    ranking_evidence_label,
)
from .model_ranking import (
    ModelRanking,
    ModelRankingEntry,
    format_ranking_model_label,
    is_plate_pose_model_path,
)
from .mobile_package_experiments import (
    DatasetRef,
    ExperimentSessionRecord,
    ExperimentModelRef,
    MobileBenchmarkReport,
    MobilePackageCandidate,
    MobilePackageExperimentStore,
    MobilePackageScore,
    MobileReportBundle,
    ReportBundleEntry,
    ReportBundleReader,
    ReportBundleValidation,
    RuntimeVariantSpec,
    build_package_candidate,
    build_package_id,
    default_runtime_variants,
    iter_full_event_rows,
    iter_full_frame_flow_rows,
    iter_full_sample_rows,
    iter_full_attempt_rows,
    iter_full_sample_annotations,
    read_mobile_sample_image,
    iter_full_thermal_rows,
    iter_full_trace_rows,
    read_mobile_report_bundle,
    read_mobile_report_bundles,
    read_alpr_package_manifest,
    read_alprmodel_manifest,
    score_mobile_report,
)
from .mobile_human_review import MobileHumanReview, MobileReviewSession, PlateTextAlignment, align_plate_text
from .mobile_mt_invocations import MtInvocationGroup

__all__ = [
    'AnnotationComparator',
    'AnnotationDiff',
    'CORNER_METRIC_SCHEMA',
    'corner_metric_protocol_descriptor',
    'evaluate_pose_corner_metrics',
    'ModelRanking',
    'ModelRankingEntry',
    'ModelComparisonCandidate',
    'ModelComparisonCatalog',
    'SCOPE_PROJECT',
    'SCOPE_WORKSPACE',
    'active_project_id_from_root',
    'comparison_scope_label',
    'normalize_comparison_scope',
    'RankingExperimentBridge',
    'RankingExperimentContext',
    'RankingExperimentParticipant',
    'EVIDENCE_CONTROLLED',
    'EVIDENCE_CONTROLLED_LEGACY',
    'EVIDENCE_LEGACY',
    'EVIDENCE_MISMATCH',
    'EVIDENCE_ORPHANED',
    'EVIDENCE_REGISTERED_INCOMPLETE',
    'EVIDENCE_WORKING',
    'RankingRegistryCompatibility',
    'RankingRegistryReconciliation',
    'ranking_evidence_label',
    'DatasetRef',
    'ExperimentSessionRecord',
    'ExperimentModelRef',
    'MobileBenchmarkReport',
    'MobilePackageCandidate',
    'MobilePackageExperimentStore',
    'MobilePackageScore',
    'MobileReportBundle',
    'MobileHumanReview',
    'MtInvocationGroup',
    'MobileReviewSession',
    'PlateTextAlignment',
    'align_plate_text',
    'ReportBundleEntry',
    'ReportBundleReader',
    'ReportBundleValidation',
    'RuntimeVariantSpec',
    'build_package_candidate',
    'build_package_id',
    'default_runtime_variants',
    'format_ranking_model_label',
    'iter_full_event_rows',
    'iter_full_frame_flow_rows',
    'iter_full_sample_rows',
    'iter_full_attempt_rows',
    'iter_full_sample_annotations',
    'read_mobile_sample_image',
    'iter_full_thermal_rows',
    'iter_full_trace_rows',
    'is_plate_pose_model_path',
    'read_alpr_package_manifest',
    'read_alprmodel_manifest',
    'read_mobile_report_bundle',
    'read_mobile_report_bundles',
    'score_mobile_report',
]
